---
language: ruby
sudo: false

rvm:
  - 2.0.0
  - 2.1.6

before_install:
  - 'gem install bundler'

script:
  - bundle install
  - bundle exec rake test

env:
  - PUPPET_VERSION="~> 3.8"
  - PUPPET_VERSION="~> 3.8" FUTURE_PARSER="yes"
  - PUPPET_VERSION="~> 4.2"
  - PUPPET_VERSION="~> 4.3"
  - PUPPET_VERSION="~> 4.4"
  - PUPPET_VERSION="~> 4.5"
  - PUPPET_VERSION="~> 4.6"
  - PUPPET_VERSION="~> 4.7"
matrix:
  fast_finish: true
